### ISSUE TITLE
lua-format install

### ISSUE THREAD

**Issue by jrock2004** [jonwalstedt/dotfiles#1]
How are you installing this formatter?

**Comment by jonwalstedt** [comment]
You need to install luaformatter ([https://github.com/Koihik/LuaFormatter](https://github.com/Koihik/LuaFormatter))

`luarocks install --server=https://luarocks.org/dev luaformatter`

I also realised that I did not have it hooked up, added missing line in https://github.com/jonwalstedt/dotfiles/commit/bf8b836ab52b8fc3b9d034123cd09f7916ced74e

**Comment by jrock2004** [comment]
Gotcha. Well it seems like that one does not compile on M1 Mac. So guess I need to wait till its fixed https://github.com/Koihik/LuaFormatter/issues/199
